name: Oryn-Tunnelv2
description: '${description}'
version: '${version}'

main: net.oryn.mc.orynTunnelv2.OrynTunnelv2
api-version: '1.21.1'
load: STARTUP

authors: [Fahry-a]

commands:
  otunnel:
    description: Oryn Tunnel management command
    usage: /otunnel <status|start|stop|update|reload|help>
    permission: otunnel.admin

permissions:
  otunnel.admin:
    description: Allows use of all Oryn Tunnel commands
    default: op
